version: "2"

services:
  coordinates:
    image: leningotru/coordinates
  encrypter:
    image: ronniemh/location-encrypt
  web:
    image: danidaniel6462/ksh_webui
    ports:
    - "8000:80"
  worker:
    image: danidaniel6462/ksh_worker
    depends_on:
      - coordinates
      - encrypter
      - redis

  redis:
    image: redis