version: "2"

services:
  coordinates:
    build: getCoordinates
    ports:
    - "8080:3000"

  encrypter:
    build: locationEncrypt
    ports:
    - "8081:8080"

  web:
    build: webui
    ports:
    - "8082:80"

  worker:
    build: worker
    depends_on:
      - coordinates
      - encrypter
      - redis

  redis:
    image: redis